apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{DEMO_NAME}}-app
  namespace: {{DEMO_NAME}}
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: {{DEMO_NAME}}-app
  template:
    metadata:
      labels:
        app: {{DEMO_NAME}}-app
    spec:
      containers:
      - name: {{DEMO_NAME}}-app
        image: {{ECR_REPO_URL}}/{{DEMO_NAME}}:{{IMAGE_TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NEO4J_URI
          value: bolt://neo4j:7687
        - name: NEO4J_USER
          value: neo4j
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-secrets
              key: neo4j-password
        - name: DEMO_ENV
          value: {{ENVIRONMENT}}
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{DEMO_NAME}}-app
  namespace: {{DEMO_NAME}}
spec:
  selector:
    app: {{DEMO_NAME}}-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{DEMO_NAME}}-ingress
  namespace: {{DEMO_NAME}}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.alpha.kubernetes.io/hostname: {{DEMO_NAME}}.{{DOMAIN_NAME}}
spec:
  rules:
  - host: {{DEMO_NAME}}.{{DOMAIN_NAME}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{DEMO_NAME}}-app
            port:
              name: http
  tls:
  - hosts:
    - {{DEMO_NAME}}.{{DOMAIN_NAME}}