name: Build and Deploy Neo4j Demos

on:
  # Run after Terraform infrastructure is deployed successfully
  workflow_run:
    workflows: ["Terraform Infrastructure Deployment"]
    types:
      - completed
    branches: [main]
  # Keep existing triggers
  # push:
  #   branches: [main]
  #   paths:
      - 'demos/**'
      - '.github/workflows/deploy-neo4j-demos.yml'
  pull_request:
    branches: [main]
    paths:
      - 'demos/**'
  workflow_dispatch:
    inputs:
      demo_name:
        description: 'Demo application name to deploy (leave empty for all demos)'
        required: false
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      deploy_all:
        description: 'Deploy all demos'
        required: false
        default: false
        type: boolean
      force_cleanup:
        description: 'Force complete namespace cleanup'
        required: false
        default: false
        type: boolean
      build_only:
        description: 'Only build and push images, skip deployment'
        required: false
        default: false
        type: boolean

jobs:
  # Skip this job if triggered by workflow_run but the upstream workflow failed
  check-upstream-status:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Terraform Status
        if: ${{ github.event_name == 'workflow_run' }}
        run: echo "Terraform infrastructure deployment was successful, proceeding with demo deployment"
      
      - name: Set success output
        id: check
        run: echo "proceed=true" >> $GITHUB_OUTPUT
    
    outputs:
      proceed: ${{ steps.check.outputs.proceed }}

  determine-demos:
    needs: [check-upstream-status]
    if: ${{ needs.check-upstream-status.outputs.proceed == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0