name: Build and Push ECR Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: ["neo4j-movie-recommendation"]  # Replace with your demo app names
        include:
          - app_name: "neo4j-movie-recommendation"
            dockerfile_path: "./neo4j-movie-recommendation"
        

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ matrix.app_name }}
        IMAGE_TAG: latest
      working-directory: ${{ matrix.dockerfile_path }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        # Update the SSM parameter with the image version
        aws ssm put-parameter \
          --name "/neo4j-demos/${{ secrets.ENVIRONMENT }}/${{ matrix.app_name }}-image-tag" \
          --value "$IMAGE_TAG" \
          --type String \
          --overwrite
